### ISSUE TITLE
MBARI MBB uuid's are stale?

### ISSUE THREAD

**Issue by Jordan-Pierce** [fathomnet/community-feedback#127]
Sorry, just causing problems for y'all. 

When trying to download images and localizations from the MBARI Monterey Bay Benthic publication on [zenodo](https://zenodo.org/record/5539915) the urls to the images lead to a 403 forbiddin error, and trying to access the images using the uuids via the api `images.find_by_uuid` gives the following error:

```python

images.find_by_uuid('705421b0-be22-4df7-a833-bd85ded9f347')
Traceback (most recent call last):
  File "C:\Users\jordan.pierce\.conda\envs\benthic\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-11a28bde4d2c>", line 1, in <module>
    images.find_by_uuid('705421b0-be22-4df7-a833-bd85ded9f347')
  File "C:\Users\jordan.pierce\.conda\envs\benthic\lib\site-packages\fathomnet\api\images.py", line 114, in find_by_uuid
    res_json = Images.get(uuid)
  File "C:\Users\jordan.pierce\.conda\envs\benthic\lib\site-packages\fathomnet\api\__init__.py", line 37, in get
    return cls.request('GET', endpoint, parse_json=parse_json, **kwargs)
  File "C:\Users\jordan.pierce\.conda\envs\benthic\lib\site-packages\fathomnet\api\__init__.py", line 30, in request
    raise ValueError('Bad request: {} {}'.format(method, url))
ValueError: Bad request: GET http://fathomnet.org:8080/images/705421b0-be22-4df7-a833-bd85ded9f347

```

Sample of from the JSON provided in zenodo:

```python
  "00_20_28_02.png": {
    "uuid": "705421b0-be22-4df7-a833-bd85ded9f347",
    "url": "http://search.mbari.org/ARCHIVE/frameGrabs/Doc%20Ricketts/images/0998/05_06_47_00.png",
    "depthMeters": 1211.25,
    "height": 0,
    "latitude": 36.41739,
    "longitude": -122.300438,
    "salinity": 34.509,
    "temperatureCelsius": 3.297,
    "oxygenMlL": 0.612,
    "pressureDbar": 1221.3,
    "timestamp": "2017-12-19 20:32:44",
    "width": 0,
    "createdTimestamp": "2017-12-19 20:32:44",
    "lastUpdatedTimestamp": "2019-02-11 12:15:54",
    "boundingBoxes": [
      {
        "uuid": "c5d4233d-b43f-40d0-d465-0aa607c4aa1e",
        "x": 797,
        "y": 384,
        "width": 277,
        "height": 454,
        "verified": true,
        "observer": "expert-observer",
        "concept": "Keratoisis"
      },
      {
        "uuid": "f3387000-0f63-4c18-586e-1da607c4aa1e",
        "x": 1387,
        "y": 328,
        "width": 216,
        "height": 250,
        "verified": true,
        "observer": "expert-observer",
        "concept": "Keratoisis"
      }
    ]
  },

```

Did I miss something?

**Comment by kevinsbarnard** [comment]
Those images and UUIDs are internal to MBARI's Video Annotation and Reference System (VARS), and are not necessarily included in FathomNet. 

From the description you linked on Zenodo:
> This model was trained on 691 classes using 33,667 localized images from MBARI’s Video Annotation and Reference System (VARS; note: only a subset of the VARS database is uploaded to FathomNet because of institutional concept embargos).
